import type { Device, NavItem, TerminalEntry } from "@/lib/simcon/types";

export const navItems: NavItem[] = [
  {
    id: "overview",
    label: "Control Overview",
    shortLabel: "OV",
    href: "#",
    active: true,
  },
  { id: "fleet", label: "Fleet Matrix", shortLabel: "FM", href: "#" },
  { id: "routes", label: "Routing Engine", shortLabel: "RE", href: "#" },
  { id: "alerts", label: "Alert Queue", shortLabel: "AQ", href: "#" },
];

export const devices: Device[] = [
  {
    id: "TRK-204",
    status: "online",
    type: "mobile",
    role: "truck",
    facility: "JKT-HUB-02",
    zone: "Gate South",
    hasGps: true,
    throughput: "18 scans/min",
    lastBeat: "4s ago",
    battery: "82%",
    connectionStatus: "connected",
    scanCooldown: 12,
  },
  {
    id: "SCN-118",
    status: "warning",
    type: "fixed",
    role: "scanner",
    facility: "JKT-HUB-02",
    zone: "Lane 04",
    hasGps: false,
    throughput: "09 scans/min",
    lastBeat: "22s ago",
    battery: "wired",
    connectionStatus: "degraded",
    scanCooldown: 18,
  },
  {
    id: "GTW-07",
    status: "online",
    type: "fixed",
    role: "gateway",
    facility: "SBY-YARD-01",
    zone: "Core Mesh",
    hasGps: false,
    throughput: "231 pkts/s",
    lastBeat: "2s ago",
    battery: "wired",
    connectionStatus: "connected",
    scanCooldown: 8,
  },
  {
    id: "TRK-188",
    status: "idle",
    type: "mobile",
    role: "truck",
    facility: "BDG-DEPOT-09",
    zone: "Buffer West",
    hasGps: true,
    throughput: "03 scans/min",
    lastBeat: "11s ago",
    battery: "59%",
    connectionStatus: "rebuilding",
    scanCooldown: 20,
  },
  {
    id: "SCN-044",
    status: "offline",
    type: "fixed",
    role: "scanner",
    facility: "MDN-HUB-03",
    zone: "Dock C2",
    hasGps: false,
    throughput: "0 scans/min",
    lastBeat: "9m ago",
    battery: "wired",
    connectionStatus: "offline",
    scanCooldown: 30,
  },
];

export const terminalEntries: TerminalEntry[] = [
  {
    id: "log-1",
    timestamp: "16:02:14.223",
    category: "HEARTBEAT",
    level: "success",
    message:
      "TRK-204 heartbeat stable. telemetry delta within nominal bounds.",
    deviceId: "TRK-204",
  },
  {
    id: "log-2",
    timestamp: "16:02:17.118",
    category: "SCAN_EVT",
    level: "info",
    message:
      "SCN-118 requested cooldown override from lane orchestration service.",
    deviceId: "SCN-118",
    badge: "QUEUED",
  },
  {
    id: "log-3",
    timestamp: "16:02:18.773",
    category: "SYS",
    level: "warning",
    message: "TRK-188 uplink degraded. mesh rejoin sequence in progress.",
    deviceId: "TRK-188",
    badge: "WATCH",
  },
  {
    id: "log-4",
    timestamp: "16:02:20.041",
    category: "TELEMETRY",
    level: "neutral",
    message: "GTW-07 packet fanout 231 pkts/s. no anomaly signature detected.",
    deviceId: "GTW-07",
  },
  {
    id: "log-5",
    timestamp: "16:02:24.556",
    category: "SCAN_EVT",
    level: "error",
    message:
      "SCN-044 command timeout. reboot rail locked until manual clearance.",
    deviceId: "SCN-044",
    badge: "BLOCKED",
  },
  {
    id: "log-6",
    timestamp: "16:02:28.882",
    category: "SYS",
    level: "info",
    message:
      "Route allocator synced 14 active lanes to control plane shadow cache.",
    deviceId: "GTW-07",
  },
];
